### ISSUE TITLE
artist/search ajax search doesn't update when no result is found.

### ISSUE THREAD

**Issue by victorpm5** [AlbertSuarez/searchly#1]
When looking for an artist and you start typing the first letters, the ajax search shows you some results.  If you keep writing and then no results are found, the ajax search keeps showing you the first results, instead of saying no results where found.

![image](https://user-images.githubusercontent.com/10065037/73138292-66449f00-4061-11ea-84ef-f9519d9bfbb6.png)

![image](https://user-images.githubusercontent.com/10065037/73138288-588f1980-4061-11ea-934b-afe4bcd37d62.png)

**Comment by AlbertSuarez** [comment]
Thanks for your issue. I'm going to take a look and see what's happening there :+1:
